### ISSUE TITLE
Case Study : Book Rental(UNIX)

### ISSUE THREAD

**Issue by Amishak150** [parthpanchal3399/Capgemini-ADAPT-Stage-2#2]
https://manipal-adapt.in.capgemini.com/?q=MULNCourseBook/listDetailedCBLearningContents/162328/cidb/full/view/50203/392447/392443/36663

https://manipal-adapt.in.capgemini.com/?q=MULNCourseBook/listDetailedCBLearningContents/162328/cidb/full/view/50204/392448/392443/36663

Please help me with these . My command is rejecting even after successful running .

**Comment by parthpanchal3399** [comment]
Hi,
I still haven't completed these since the questions are either wrong or the testcases are wrong. Will add it as soon as I get the solution
